### ISSUE TITLE
Racc::ParseError: parse can be raised for correct SQL statements.

### ISSUE THREAD

**Issue by tanasegabriel** [square/mysql-parser#5]
When trying to parse a alter table query containing `DEFAULT 0 NOT NULL`, `Racc::ParseError:
parse error on value "NOT" (NOT)` is raised. According to [the MySQL documentation](https://dev.mysql.com/doc/refman/5.5/en/alter-table-examples.html), this query is using the correct syntax.

Interestingly, if we replace `DEFAULT 0 NOT NULL` with `NOT NULL DEFAULT 0`, the parsing is successful.

```ruby
irb(main):001:0> require 'mysql-parser'
=> true
irb(main):002:0> query = "ALTER TABLE `some_table` ADD `something` int DEFAULT 0 NOT NULL"
=> "ALTER TABLE `some_table` ADD `something` int DEFAULT 0 NOT NULL"
irb(main):003:0> MySQLParser.new.parse(query)
Racc::ParseError:
parse error on value "NOT" (NOT)
	from /Users/gabrieltanase/.rbenv/versions/2.4.5/lib/ruby/2.4.0/racc/parser.rb:528:in `on_error'
	from /Users/gabrieltanase/.rbenv/versions/2.4.5/lib/ruby/2.4.0/racc/parser.rb:259:in `_racc_do_parse_c'
	from /Users/gabrieltanase/.rbenv/versions/2.4.5/lib/ruby/2.4.0/racc/parser.rb:259:in `do_parse'
	from /Users/gabrieltanase/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/mysql-parser-0.0.3/lib/lexer.rb:29:in `scan_str'
	from mysql.y.rb:1288:in `parse'
	from (irb):3
	from /Users/gabrieltanase/.rbenv/versions/2.4.5/bin/irb:11:in `<main>'
irb(main):004:0>
irb(main):005:0*
irb(main):006:0* query = "ALTER TABLE `some_table` ADD `something` int NOT NULL DEFAULT 0"
=> "ALTER TABLE `some_table` ADD `something` int NOT NULL DEFAULT 0"
irb(main):007:0> MySQLParser.new.parse(query)
=> {:tree=><root: [<S: [" "]>, <r_commands: [<r_ALTER_TABLE: ["ALTER", <S: [" "]>, <r_ONLINE_OFFLINE: []>, <r_opt_IGNORE: []>, "TABLE", <S: [" "]>, <r_tbl_name: [<r_tbl_name_int: [<ident: ["`", <opt_ident_in_backtick: [<opt_ident_in_backtick: []>, "some_table"]>, "`", <S: [" "]>]>]>]>, <r_opt_alter_commands: [<r_comma_separated_alter_specification: [<r_alter_specification: ["ADD", <S: [" "]>, <r_opt_COLUMN: []>, <r_col_name: [<ident: ["`", <opt_ident_in_backtick: [<opt_ident_in_backtick: []>, "something"]>, "`", <S: [" "]>]>]>, <r_column_definition: [<r_datatype: ["int", <S: [" "]>, <r_opt_datatype_int: [<r_opt_length_int: []>, <r_opt_UNSIGNED: []>, <r_opt_ZEROFILL: []>]>]>, <r_opt_NULL_status: ["NOT", <S: [" "]>, <null: ["NULL", <S: [" "]>]>]>, <r_opt_DEFAULT_with_val: ["DEFAULT", <S: [" "]>, <value: [<number: [<integer: [<nat: [<binary: ["0", <S: [" "]>]>]>]>]>]>]>, <r_opt_AUTO_INCREMENT: []>, <r_opt_UNIQUE_or_PRIMARY: []>, <r_opt_COMMENT_with_val: []>, <r_opt_COLUMN_FORMAT: []>, <r_opt_STORAGE: []>, <r_opt_COLUMN_ON_UPDATE: []>]>, <r_opt_pos_column: []>]>]>]>, <r_opt_after_alter: []>, <r_opt_PARTITION_options: []>]>]>]>, :state=>{}}
```

Seems related to https://github.com/square/mysql-parser/blob/master/mysql.y.rb#L418-L422

**Comment by michaelfinch** [comment]
The parser is unfortunately super strict. It follows the grammar described in https://dev.mysql.com/doc/refman/5.6/en/alter-table.html and https://dev.mysql.com/doc/refman/5.6/en/create-table.html. If you click that second link, you'll see that  the syntax for a column definition is
```
column_definition:
    data_type [NOT NULL | NULL] [DEFAULT default_value]
```
I'd definitely accept PRs that make this better.

**Comment by Aliciawyse** [comment]
Hey there! I'm going to give this a shot!

**Comment by michaelfinch** [comment]
I believe this was already fixed in https://github.com/square/mysql-parser/pull/6. Let me confirm

**Comment by michaelfinch** [comment]
Confirmed, this is fixed now
