### ISSUE TITLE
CREATE VIEW parsing issue 

### ISSUE THREAD

**Issue by robertomczak** [square/mysql-parser#8]
Hi, Fallowing spec does not work as expected: 
```
    it 'tests for create view' do
      @result = @evaluator.parse('CREATE VIEW asd AS select * FROM def')
      test.to eq(' CREATE VIEW asd AS select * FROM def ')
    end
```

```
 1) Testing the Parser tests for create view
     Failure/Error: raise  ScanError, "can not match: '" + text + "'"
     
     MySQLParser::ScanError:
       can not match: '* FROM def '
     # ./lib/lexer.rb:635:in `_next_token'
     # ./lib/lexer.rb:50:in `next_token'
     # ./lib/lexer.rb:726:in `tokenize'
     # mysql.y.rb:1284:in `parse'
     # ./spec/parser_spec.rb:63:in `block (2 levels) in <class:MySQLParserTester>'
```

**Comment by michaelfinch** [comment]
Did you write that spec yourself? According to the README, CREATE VIEW is not currently supported: https://github.com/square/mysql-parser#mysqlparser. Feel free to make a PR if you want to add support for it.

**Comment by robertomczak** [comment]
@michaelfinch Yes, this was written manually in order to check support for CREATE VIEW of SHIFT  UI https://github.com/square/shift/blob/master/ui/spec/unit/osc_parser_spec.rb
